events {}

http {
    upstream backend_servers {
        least_conn;

        server sistema-distribuidos-trabajo-2.onrender.com:443;
        server sistema-distribuidos-trabajo-2-1.onrender.com:443;
    }

    server {
        listen 10000;

        location / {
            proxy_pass https://backend_servers;

            proxy_ssl_server_name on;  # 👈 MUY IMPORTANTE

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}